baseURL = "https://blog.markusbilz.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "I'm Markus Bilz"
theme = ["anatole", "hugo-simplecite"]
summarylength = 10
enableEmoji = true
math=true

[params]
author = "Markus Bilz"
description = "Data Scientist Â· Learner ðŸŒ±"
profilePicture = "images/profile.jpg"
keywords = "Bilz, Markus, DHBW, KIT, Atruvia, Computer Science Student, Commercial Computer Scientist, Karlsruhe"
favicon = "favicons/"
customCss = ["css/custom.css", "css/lightbox.css"]
customJs = ["js/lightbox.js"]

[params.repository]
branch = 'master'
owner = 'KarelZe'
repo = 'blog'
service = 'GitHub'
urlPatternEdit = 'https://github.com/%s/%s/edit/%s/%s'
urlPatternView = 'https://github.com/%s/%s/blob/%s/%s'

[params.umami]
serverURL = "insights.alexbilz.com"
id = "ab202af5-def1-4588-b563-c99e8e695f9d"
trackerScriptName = "script.js"


## Set as many as you want.

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/karelze"

[[params.socialIcons]]
icon = "fab fa-stack-overflow"
title = "Stackoverflow"
url = "https://stackoverflow.com/users/5755604/karelze"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/markus-bilz/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:web@markusbilz.com"

[params.giscus]
repo = "karelze/blog"
repoId = "MDEwOlJlcG9zaXRvcnkyNTUwMjk2MzY="
category = "General"
categoryId = "DIC_kwDODzNxhM4Crbuf"
mapping = "pathname"
strict = false
reactionsEnabled = true
emitMetadata = false
inputPosition = "bottom"
theme = "dark"
lang = "en"
loading = "lazy"



[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "CV"
  weight = 300
  identifier = "cv"
  url = "/documents/cv_en.pdf"

  [[menu.footer]]
  name = "legal notice"
  weight = 1
  identifier = "legal_notice"
  url = "/legal_notice/"

[markup]
  [markup.highlight]
    style = "github-dark"
    codeFences = true
    guessSyntax = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[mermaid]
enable = true
